import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {TopNavigation} from "@/components/TopNavigation";
import Navigation from "@/components/Navigation";
import {Providers} from "@/components/Providers";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
      <Providers>
        <Navigation>
          <div className="container mx-auto mt-1">{children}</div>
        </Navigation>
      </Providers>
      </body>
    </html>
  )
}
