import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import Navigation from '@/components/Navigation';
import { Providers } from '@/components/Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
	<html lang="en">
		<body className={`${inter.className}`}>
			<Providers>
				<Navigation>{children}</Navigation>
			</Providers>
		</body>
	</html>
);

export default RootLayout;
